name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test

      - name: Start backend server
        run: |
          cd backend
          npm start &
        env:
          MONGO_URL: mongodb://localhost:27017/testdb # Falls benötigt

      - name: Run Cypress tests
        run: |
          cd frontend
          npx cypress run
